import { Milestone, Project } from './types';

// 从CSV文件中提取的里程碑数据
export const milestoneData: Milestone[] = [
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "高对比度超结构光栅面发射激光及光子集成芯片的基础研究项目",
    name: "第一阶段",
    startDate: "2023/1/10",
    endDate: "2024/1/9",
    evaluationDate: "2024/1/9",
    actualEvaluationDate: "2024/11/28 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "高对比度超结构光栅面发射激光及光子集成芯片的基础研究项目",
    name: "第二阶段",
    startDate: "2024/1/10",
    endDate: "2025/1/9",
    evaluationDate: "2025/1/9",
    actualEvaluationDate: ""
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "高对比度超结构光栅面发射激光及光子集成芯片的基础研究项目",
    name: "第三阶段",
    startDate: "2025/1/10",
    endDate: "2026/1/9",
    evaluationDate: "2026/1/9",
    actualEvaluationDate: ""
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "高可靠性氮化镓功率器件机理及其上新型工业电源架构的研究",
    name: "第一阶段",
    startDate: "2021/9/1",
    endDate: "2022/8/31",
    evaluationDate: "2022/8/31",
    actualEvaluationDate: "2022/9/29 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "高可靠性氮化镓功率器件机理及其上新型工业电源架构的研究",
    name: "第二阶段",
    startDate: "2022/9/1",
    endDate: "2023/8/31",
    evaluationDate: "2023/8/31",
    actualEvaluationDate: "2023/11/14 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "高可靠性氮化镓功率器件机理及其上新型工业电源架构的研究",
    name: "第三阶段",
    startDate: "2023/9/1",
    endDate: "2024/8/31",
    evaluationDate: "2024/8/31",
    actualEvaluationDate: "2024/11/22 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "香港中文大学（深圳）未来智联网络研究院项目",
    name: "第一阶段",
    startDate: "2021/12/1",
    endDate: "2022/11/30",
    evaluationDate: "2022/11/30",
    actualEvaluationDate: "2022/12/22 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "香港中文大学（深圳）未来智联网络研究院项目",
    name: "第二阶段",
    startDate: "2022/12/1",
    endDate: "2023/11/30",
    evaluationDate: "2023/11/30",
    actualEvaluationDate: "2024/1/24 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "香港中文大学（深圳）未来智联网络研究院项目",
    name: "第三阶段",
    startDate: "2023/12/1",
    endDate: "2024/11/30",
    evaluationDate: "2024/11/30",
    actualEvaluationDate: ""
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "香港中文大学（深圳）未来智联网络研究院项目",
    name: "第四阶段",
    startDate: "2024/12/1",
    endDate: "2025/11/30",
    evaluationDate: "2025/11/30",
    actualEvaluationDate: ""
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "香港中文大学（深圳）未来智联网络研究院项目",
    name: "第五阶段",
    startDate: "2025/12/1",
    endDate: "2026/11/30",
    evaluationDate: "2026/11/30",
    actualEvaluationDate: ""
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "基于微纳技术的肿瘤精准诊疗技术研发与应用项目",
    name: "第一阶段",
    startDate: "2021/7/1",
    endDate: "2022/6/30",
    evaluationDate: "2022/6/30",
    actualEvaluationDate: "2022/9/22 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "基于微纳技术的肿瘤精准诊疗技术研发与应用项目",
    name: "第二阶段",
    startDate: "2022/7/1",
    endDate: "2023/6/30",
    evaluationDate: "2023/6/30",
    actualEvaluationDate: "2023/11/27 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "基于微纳技术的肿瘤精准诊疗技术研发与应用项目",
    name: "第三阶段",
    startDate: "2023/7/1",
    endDate: "2024/6/30",
    evaluationDate: "2024/6/30",
    actualEvaluationDate: ""
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "大湾区生物医药研发创新中心项目",
    name: "第一阶段",
    startDate: "2020/12/1",
    endDate: "2021/11/30",
    evaluationDate: "2021/11/30",
    actualEvaluationDate: "2022/4/8 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "大湾区生物医药研发创新中心项目",
    name: "第二阶段",
    startDate: "2021/12/1",
    endDate: "2022/11/30",
    evaluationDate: "2022/11/30",
    actualEvaluationDate: "2023/3/24 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理",
    projectName: "大湾区生物医药研发创新中心项目",
    name: "第三阶段",
    startDate: "2022/12/1",
    endDate: "2023/11/30",
    evaluationDate: "2023/11/30",
    actualEvaluationDate: "2024/10/23 0:00:00"
  },
  {
    batch: "河套深港科技合作区高端科研项目管理（第二批）",
    projectName: "高速率（112Gbs）光传输用VCSEL光芯片关键技术研发及应用项目",
    name: "第一阶段",
    startDate: "2024/1/10",
    endDate: "2025/1/9",
    evaluationDate: "2025/1/9",
    actualEvaluationDate: ""
  },
  {
    batch: "河套深港科技合作区高端科研项目管理（第二批）",
    projectName: "高速率（112Gbs）光传输用VCSEL光芯片关键技术研发及应用项目",
    name: "第二阶段",
    startDate: "2025/1/10",
    endDate: "2026/1/9",
    evaluationDate: "2026/1/9",
    actualEvaluationDate: ""
  },
  {
    batch: "河套深港科技合作区高端科研项目管理（第二批）",
    projectName: "高速率（112Gbs）光传输用VCSEL光芯片关键技术研发及应用项目",
    name: "第三阶段",
    startDate: "2026/1/10",
    endDate: "2027/1/9",
    evaluationDate: "2027/1/9",
    actualEvaluationDate: ""
  }
];

// 从CSV文件中提取的项目基本信息数据
export const projectData: Project[] = [
  {
    id: "1",
    batch: "河套深港科技合作区高端科研项目管理（第二批）",
    name: "14nm技术节点良率综合优化系统",
    client: "河套发展署",
    organization: "深圳晶源信息技术有限公司",
    industry: "半导体与集成电路",
    startDate: "2024/4/1 0:00:00",
    endDate: "2027/3/31 0:00:00",
    progressStatus: "",
    managementStatus: "进行中",
    projectManager: "饶龙记",
    projectSpecialist: "",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 5000,
    selfFunding: 5300,
    location: "深圳市福田区河套深港科技创新合作区深圳园区福保街道福保社区槟榔道3号深港国际科技园D座11层",
    description: "聚焦于开发一套针对14nm 技术节点良率驱动的芯片设计与制造综合优化 EDA 系统，主要应用于光刻掩模版设计优化、工艺条件和设备参数的优化、芯片设计可制造性分析等情形。该系统立足于先进的 OPC技术，将系统扩展至芯片设计和制造领域，建立一套综合良率提升系统平台，为晶圆代工厂商提供良率解决方案，并预期在项目建设期内完成 5000 万元订单，申请发明专利20项。项目的实施和成功推广可为国产14nm 芯片制造提供量体裁衣的解决方案，助力我国在高端芯片制造领域的技术自主可控，提高我国在集成电路制造领域的国际竞争力。",
    background: "内地背景企业科研项目",
    internalManager: "徐玲艳",
    newStaff: 0,
    currentStaff: 10,
    formerStaff: 0,
    patentTarget: 20,
    patentPublished: 0,
    paperTarget: 0,
    paperPublished: 0,
    projectLeader: "施伟杰",
    leaderContact: "",
    plannedStaff: 10,
    milestones: []
  },
  {
    id: "2",
    batch: "河套深港科技合作区高端科研项目管理（第二批）",
    name: "新一代TCAD工具平台",
    client: "河套发展署",
    organization: "理芯科技（深圳）有限公司",
    industry: "半导体与集成电路",
    startDate: "2024/3/1 0:00:00",
    endDate: "2027/2/28 0:00:00",
    progressStatus: "",
    managementStatus: "进行中",
    projectManager: "李扬",
    projectSpecialist: "",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 2000,
    selfFunding: 2000,
    location: "深圳市福田区河套深港科技创新合作区深圳园区福保街道福保社区市花路32号香港科学园深圳分园4层405室",
    description: "针对先进节点的纳米尺度器件、显示面板的薄膜晶体管（TFT）器件、第三代半导体器件，研发所需的TCAD 仿真理论、方法和工具，开发先进高精度的物理仿真方法及模型，结合经典半导体器件及制程仿真（TCAD）及原子级量子TCAD，开发一套达到国际领先水平的 TCAD 仿真软件平台，为国内现有及未来的半导体器件/工艺的发展提供先进、高效、易用的 EDA 工具支持。项目将充分填补国内 EDA 工具链的空白,为先进半导体技术节点提供最前沿的 EDA 支持，提高我国晶圆厂的设计水平和良率，助力我国新一代电子器件、电子材料的研发。",
    background: "内地背景企业科研项目",
    internalManager: "徐玲艳",
    newStaff: 0,
    currentStaff: 14,
    formerStaff: 0,
    patentTarget: 8,
    patentPublished: 0,
    paperTarget: 4,
    paperPublished: 0,
    projectLeader: "陈冠华",
    leaderContact: "",
    plannedStaff: 12,
    milestones: []
  },
  {
    id: "3",
    batch: "河套深港科技合作区高端科研项目管理（第二批）",
    name: "高速率（112Gbs）光传输用VCSEL光芯片关键技术研发及应用项目",
    client: "河套发展署",
    organization: "深圳市嘉敏利光电有限公司",
    industry: "半导体与集成电路",
    startDate: "2024/4/1 0:00:00",
    endDate: "2027/1/9 0:00:00",
    progressStatus: "",
    managementStatus: "进行中",
    projectManager: "饶龙记",
    projectSpecialist: "",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 2000,
    selfFunding: 7650,
    location: "深圳市福田区河套深港科技创新合作区深圳园区福保街道福保社区红柳道2号顺丰工业厂房1层B125房",
    description: "面向短距离光互联的低功耗、高速、高可靠性传输的应用场景，结合当前国内VCSEL光芯片的技术和市场现状，重点对标美国博通（Broadcom）公司的850nm100Gb/s高速VCSEL芯片产品，开展对低功耗、高速（112Gb/s）、高可靠性（MTTF& gt;5,000H）VCSEL关键技术及其产业化应用的研究，解决VCSEL在低功耗条件下的高频响应和长期工作的可靠性等重要技术问题，实现低功耗、高速、高可靠性 VCSEL光芯片从设计到制程等全过程的自主可控，并最终形成产业化制造能力。研制的VCSEL芯片可广泛应用于5G/6G、大数据应用的800G-1.2T架构数据中心，以及A0C、超高清视频传输等消费电子领域，解决在该领域中关键芯片从技术到供应端受制于欧美的卡脖子技术难题，同时，项目的实施将会培育一批半导体、集成电路紧缺工程人才，提高国内在该领域的整体科学研究能力和技术水平。",
    background: "内地背景企业科研项目",
    internalManager: "徐玲艳",
    newStaff: 0,
    currentStaff: 31,
    formerStaff: 0,
    patentTarget: 10,
    patentPublished: 0,
    paperTarget: 3,
    paperPublished: 0,
    projectLeader: "张立永",
    leaderContact: "",
    plannedStaff: 11,
    milestones: []
  },
  {
    id: "4",
    batch: "河套深港科技合作区高端科研项目管理",
    name: "基于新靶点作用机理创新药关键技术及应用研究项目单位",
    client: "河套发展署",
    organization: "深圳信立泰药业股份有限公司",
    industry: "生物医药",
    startDate: "2022/3/1 0:00:00",
    endDate: "2025/7/31 0:00:00",
    progressStatus: "正常",
    managementStatus: "进行中",
    projectManager: "李扬",
    projectSpecialist: "罗程",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 5000,
    selfFunding: 5016.65,
    location: "深圳市福田区福保街道福保社区红柳道2号289数字半岛4层A区",
    description: "针对炎症性肠病、银屑病、类风湿关节炎和肾小球肾炎等自身免疫性疾病，开发具有依从性好、服用方便、患者用药成本低等特点的口服小分子药物，为自身免疫性疾病患者提供新治疗方案，推动我国在自身免疫性疾病治疗药物领域实现重大突破。",
    background: "内地背景企业科研项目",
    internalManager: "袁伟翔",
    newStaff: 0,
    currentStaff: 34,
    formerStaff: 0,
    patentTarget: 10,
    patentPublished: 23,
    paperTarget: 0,
    paperPublished: 0,
    projectLeader: "吴俊军",
    leaderContact: "",
    plannedStaff: 34,
    milestones: []
  },
  {
    id: "5",
    batch: "河套深港科技合作区高端科研项目管理",
    name: "基于机器学习的智能网联汽车感知、定位仿真、协同决策核心算法及计算平台研究项目",
    client: "河套发展署",
    organization: "深圳元戎启行科技有限公司",
    industry: "智能网联汽车",
    startDate: "2021/9/1 0:00:00",
    endDate: "2024/8/31 0:00:00",
    progressStatus: "正常",
    managementStatus: "已完结",
    projectManager: "饶泽鸿",
    projectSpecialist: "",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 4680,
    selfFunding: 4689,
    location: "深港国际科技园 C栋7层-8层",
    description: "基于机器学习的智能网联汽车感知、定位、仿真、协同决策核心算法及计算平台研究，以切实提高智能网联汽车环境感知性能、定位精度和协同决策合理性为目的，围绕多传感器信息融合的复杂环境感知、基于深度学习的高精度地图绘制与融合定位、数据驱动的自动驾驶智能仿真、智能网联汽车云控系统建模与协同决策控制开展基础理论研究，攻克智能网联汽车感知、定位、仿真、协同决策核心算法及计算平台等关键核心技术。充分发挥车路云一体化系统在融合感知决策规划方面的优势，弥补单车自动驾驶和传统车路协同的性能不足，切实提高智能汽车行驶安全性、可靠性和稳定性。项目成果将为智能网联汽车融合感知、高精定位、联合仿真与协同决策技术研发奠定关键共性技术基础，推动智能网联车路云一体化融合的应用和发展。",
    background: "内地背景企业科研项目",
    internalManager: "刘涛",
    newStaff: 0,
    currentStaff: 31,
    formerStaff: 0,
    patentTarget: 90,
    patentPublished: 0,
    paperTarget: 9,
    paperPublished: 0,
    projectLeader: "周光",
    leaderContact: "",
    plannedStaff: 11,
    milestones: []
  },
  {
    id: "6",
    batch: "河套深港科技合作区高端科研项目管理",
    name: "香港中文大学（深圳）未来智联网络研究院项目",
    client: "河套发展署",
    organization: "香港中文大学（深圳）",
    industry: "宽带网络通信",
    startDate: "2021/10/26 0:00:00",
    endDate: "2026/11/30 0:00:00",
    progressStatus: "正常",
    managementStatus: "进行中",
    projectManager: "李扬",
    projectSpecialist: "",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 5175,
    selfFunding: 5000,
    location: "/",
    description: "两大领域建设：1、应用基础研究方面:研究高能效超可靠低时延通信技术，B5G/6G高能效智能网络理论与架构，5G与B5G核心器件与芯片技术;2、科研平台建设与产业应用:建设宽带通信多场景云网创新测试环境、5G+智联网络应用验证平台、毫米波集成电路创新科研实验平台。",
    background: "香港背景高校科研项目",
    internalManager: "张帆",
    newStaff: 23,
    currentStaff: 78,
    formerStaff: 34,
    patentTarget: 15,
    patentPublished: 23,
    paperTarget: 60,
    paperPublished: 119,
    projectLeader: "崔曙光",
    leaderContact: "",
    plannedStaff: 45,
    milestones: []
  },
  {
    id: "7",
    batch: "河套深港科技合作区高端科研项目管理",
    name: "基于微纳技术的肿瘤精准诊疗技术研发与应用项目",
    client: "河套发展署",
    organization: "香港城市大学深圳福田研究院",
    industry: "生物医药",
    startDate: "2021/7/1 0:00:00",
    endDate: "2024/6/30 0:00:00",
    progressStatus: "正常",
    managementStatus: "进行中",
    projectManager: "饶泽鸿",
    projectSpecialist: "李扬",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 5000,
    selfFunding: 5000,
    location: "xxxxx",
    description: "瞄准精准医学领域关键基础信息及核心技术、仪器和方法等一系列重大的前沿问题，研究肿瘤精准诊疗的创新诊断技术及创新治疗药物。项目的成功实施将有助于我国肿瘤精准医学领域的跨学科合作，为我国精准医学产业培养人才，打造以肿瘤精准诊断与治疗为中心的国际合作交流平台。",
    background: "香港背景高校科研项目",
    internalManager: "高加俊",
    newStaff: 0,
    currentStaff: 35,
    formerStaff: 0,
    patentTarget: 3,
    patentPublished: 9,
    paperTarget: 5,
    paperPublished: 14,
    projectLeader: "杨梦甦",
    leaderContact: "",
    plannedStaff: 11,
    milestones: []
  },
  {
    id: "8",
    batch: "河套深港科技合作区高端科研项目管理",
    name: "高可靠性氮化镓功率器件机理及其上新型工业电源架构的研究",
    client: "河套发展署",
    organization: "深圳智芯微电子科技有限公司",
    industry: "半导体与集成电路",
    startDate: "2021/9/1 0:00:00",
    endDate: "2024/8/31 0:00:00",
    progressStatus: "正常",
    managementStatus: "已完结",
    projectManager: "饶泽鸿",
    projectSpecialist: "李扬",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 2600,
    selfFunding: 2600,
    location: "/",
    description: "开展高可靠性氨化镓功率器件机理及其上新型工业电源架构的研究，包括外延层缺陷产生机理研究、基于密度泛函的氮化镓功率器件模型建立与计算研究、高耐压低导通电阻的氮化镓功率开关器件制备研究与验证、氮化镓功率器件可靠性与失效机理研究、氮化镓电路驱动设计研究、氮化镓器件电源架构的研究、氮化镓器件电源系统可靠性的研究工作。基于以上研究内容解决氮化镓功率器件材料外延机理、工艺制备、器件封装测试和驱动电路中的关键科学问题，形成本领域领先的技术成果及技术专利，基于技术专利成果、器件可靠性研究与模型建立，结合电源系统设计和仿真结果，实现氮化镓工业电源架构，通过验证氮化镓方案电源架构在工业设备上的应用效果，验证项目研究内容及成果。",
    background: "内地背景企业科研项目",
    internalManager: "徐玲艳",
    newStaff: 0,
    currentStaff: 32,
    formerStaff: 0,
    patentTarget: 17,
    patentPublished: 18,
    paperTarget: 19,
    paperPublished: 19,
    projectLeader: "王祥",
    leaderContact: "",
    plannedStaff: 15,
    milestones: []
  },
  {
    id: "9",
    batch: "河套深港科技合作区高端科研项目管理",
    name: "面向行业赋能的计算机视觉关键技术研究项目",
    client: "河套发展署",
    organization: "商汤人工智能研究中心（深圳）有限公司",
    industry: "超高清视频显示",
    startDate: "2021/6/25 0:00:00",
    endDate: "2024/6/24 0:00:00",
    progressStatus: "正常",
    managementStatus: "已完结",
    projectManager: "饶龙记",
    projectSpecialist: "",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 4400,
    selfFunding: 6600,
    location: "深圳市福田保税区深九科技创业园（深港国际科技园）大厦6（C）栋11-12层01-06号",
    description: "依托商汤科技在深度学习和计算机视觉等领域深厚的研发积累和在多个行业深耕落地的经验，旨在解决计算机视觉技术在行业高效赋能中的关键问题。本项目针对计算机视觉面向行业高效率赋能的关键技术问题，比如模型训练高性能优化、长尾模型数据仿真生产、小样本通用视觉模型训练以及面向全硬件平台的适配部署进行深入研究，并构建一套高效通用的计算机视觉模型训练和部署的技术平台体系。基于上述支撑性的基础研究，商汤进一步解决在计算机视觉研究技术落地中最有挑战的两个场景共同面临的关键技术问题，即智慧城市和工业视觉场景中如何解决开集长尾的小样本问题。",
    background: "香港背景企业科研项目",
    internalManager: "张帆",
    newStaff: 58,
    currentStaff: 89,
    formerStaff: 0,
    patentTarget: 20,
    patentPublished: 0,
    paperTarget: 10,
    paperPublished: 0,
    projectLeader: "王晓刚",
    leaderContact: "",
    plannedStaff: 31,
    milestones: []
  },
  {
    id: "10",
    batch: "河套深港科技合作区高端科研项目管理",
    name: "低功耗、高速、高可靠性VCSEL光芯片机理研究项目",
    client: "河套发展署",
    organization: "深圳市德明利光电有限公司",
    industry: "半导体与集成电路",
    startDate: "2020/11/1 0:00:00",
    endDate: "2023/10/31 0:00:00",
    progressStatus: "正常",
    managementStatus: "已完结",
    projectManager: "饶龙记",
    projectSpecialist: "",
    fundingSource: "财政资助+自筹资金",
    governmentFunding: 3400,
    selfFunding: 4600,
    location: "深港科技创新合作区深圳园区289数字半岛产业园1层B125",
    description: "开展低功耗、高速、高可靠性VCSEL 光芯片机理与关键技术研究，一是研究新型穿隧式低阻抗 DBR 结合DBR-MOW应力适配的 VCSEL 外延看构方法，揭示VCSEL的高速调制机理;二是研究基于模态及光场控制的集成微透镜机制，结合高散热金属键合方法，解决高速 VCSEL 光电性能输出稳定性与长期工作条件下的可靠性问题；三是构建高速 VCSEL 光芯片模型，完成高速 VCSEL 机理与关键技术的论证,最终提出低功耗、高速、高可靠性 VCSEL机理与技术实现方案。",
    background: "内地背景企业科研项目",
    internalManager: "徐玲艳",
    newStaff: 0,
    currentStaff: 44,
    formerStaff: 0,
    patentTarget: 30,
    patentPublished: 0,
    paperTarget: 6,
    paperPublished: 0,
    projectLeader: "吴国梅",
    leaderContact: "",
    plannedStaff: 20,
    milestones: []
  }
];

// 将里程碑数据与项目数据关联起来
export function associateMilestonesWithProjects(): Project[] {
  const projectsWithMilestones = projectData.map(project => {
    const projectMilestones = milestoneData.filter(
      milestone => milestone.projectName === project.name && milestone.batch === project.batch
    );
    return {
      ...project,
      milestones: projectMilestones
    };
  });
  return projectsWithMilestones;
}

// 获取关联后的项目数据
export const projectsWithMilestones = associateMilestonesWithProjects();

// 计算项目进度
export function calculateProjectProgress(project: Project): number {
  if (!project.milestones || project.milestones.length === 0) {
    return 0;
  }
  
  const totalMilestones = project.milestones.length;
  const completedMilestones = project.milestones.filter(
    milestone => milestone.actualEvaluationDate && milestone.actualEvaluationDate.trim() !== ''
  ).length;
  
  return Math.round((completedMilestones / totalMilestones) * 100);
}

// 获取带有进度信息的项目数据
export const projectsWithProgress = projectsWithMilestones.map(project => ({
  ...project,
  progress: calculateProjectProgress(project)
})); 